(* ========================================================================= *)
(* EXIT-BLOCK proof progress (2026-06-23) — the LAST goal of cheat-free        *)
(* MLDSA_REJ_UNIFORM_ETA4_CORRECT. Starts from CORRECT_SCAFFOLD_TAC's leftover  *)
(* goal (after ABBREV q = 16*(N-1)). Entry @ pc+52: RAX=word(niblen(q)),        *)
(* RCX=word q, res holds REJ(SUB(0,q)), YMM2/3/4 set; hyps q<=256,              *)
(* niblen(q)<=248 (REJ_NIBBLES + REJ_SAMPLE forms), 16N=q+16, q+16<=272.        *)
(*                                                                            *)
(* VALIDATED PREFIX (head guards, both fall through):                          *)
(*   ENSURES_INIT_TAC "s0" THEN                                                *)
(*   <JA_NOT_TAKEN_LE fact for cmp eax,248 @ niblen(q)<=248> THEN              *)
(*   <JA_NOT_TAKEN_LE fact for cmp ecx,256 @ q<=256> THEN                      *)
(*   X86_STEPS_TAC EXEC (1--4)  ==> RIP s4 = pc+75 (vpmovzxbw, sub-iter1 start) *)
(* The two JA facts (exact terms):                                            *)
(*  ~(&(val(word_zx(word(LENGTH(REJ_SAMPLE_ETA4_BYTES(SUB_LIST(0,q)inlist):int32 list)):int64):int32)):int - &248 = &(val(word_sub(word_zx(word(LENGTH ...):int64):int32)(word 248):int32))) \/ val(word_sub ...)=0   [MATCH_MP_TAC JA_NOT_TAKEN_LE; ARITH] *)
(*  ~(&(val(word_zx(word q:int64):int32)):int - &256 = &(val(word_sub(word_zx(word q:int64):int32)(word 256):int32))) \/ val(...)=0   [JA_NOT_TAKEN_LE; q<=256] *)
(*                                                                            *)
(* REMAINING (the genuine work): 4 sub-iters from pc+75. Each sub-iter k        *)
(* (k=0..3, at pos q+4k) does gather+store+counter then a `cmp eax,248; ja`     *)
(* mid-guard (sub-iters 1,2,3) or wraps to head (sub-iter 4 -> jmp pc+52 then   *)
(* head guard). At sub-iter k's guard: ASM_CASES_TAC on whether                 *)
(* niblen(q+4(k+1)) > 248 (count-exit) OR q+4(k+1) reaches 256 (offset):        *)
(*   - NOT taken: continue (reuse SI{k+1} gather/store/fold from .si*_full /    *)
(*     .si*_fold_*; they fold the store into res prefix and resolve the guard   *)
(*     not-taken via JA_NOT_TAKEN_LE -- ALREADY the SIk_MG_TAC/SIk_RESOLVE      *)
(*     pattern).                                                                *)
(*   - TAKEN: resolve RIP COND -> pc+314 via JA_TAKEN_GT (in .subiter_bridge_   *)
(*     lemmas.ml), with exit position p=q+4(k+1) [or q for the entry head, but  *)
(*     that's not taken since niblen(q)<=248]; establish niblen(p)<=256 via     *)
(*     OUTLEN0_LE_256_FROM_SUBITER; then MP_TAC                                 *)
(*     MLDSA_REJ_UNIFORM_ETA4_SCALAR_TAIL_AT_P @ (concrete p) and discharge     *)
(*     pc+314 -> pc+402 (ENSURES_TRANS / sequence).                            *)
(* NOTE the offset-exit (q reaches 256) only matters when 256<16N (N=17,        *)
(* pos=272 region); the count-exit (niblen>248) is the common case. The WOP     *)
(* hyp `256<16*N \/ 248<niblen(16N)` (with 16N=q+16) guarantees SOME guard      *)
(* fires within this block (else the block completes clean and the next head    *)
(* guard at pos q+16=16N fires).                                                *)
(*                                                                            *)
(* The SI{1,2,3,4} tactics are loaded (.si*_full, .si*_integrated,             *)
(* .si*_fold_*). They were built for the CLEAN body (all-not-taken). For the    *)
(* exit block, the LAST sub-iter before exit needs the TAKEN branch instead --  *)
(* adapt SIk_RESOLVE to resolve the COND via JA_TAKEN_GT (then SCALAR_TAIL_AT_P)*)
(* rather than JA_NOT_TAKEN_LE. *)
(* ========================================================================= *)
Printf.printf "EXIT_BLOCK_PROGRESS: head guards validated (pc+52 -> pc+75); 4 sub-iters + per-guard exit branches remain. See comment.\n";;

(* ⚠️ PERFORMANCE (2026-06-23): raw X86_VSTEPS_TAC over the SIMD gather is FAR  *)
(* too slow -- 6 vector instrs (pc+75..pc+102: vpmovzxbw/vpand/vpshufb/...)     *)
(* took ~286s. MUST use the specialized CLEAN_BODY vector tactics instead:      *)
(* PREFIX_G_FULL_TAC (head+sub-iter1 -> s23) and SI2/3/4_INTEGRATED, which      *)
(* REABBREV the vector intermediates (f0sub/f1bnd/chunk0/mask8/pshuf/tab) and   *)
(* avoid the term blowup. The exit block should be proven by RE-RUNNING those   *)
(* SAME tactics (they step pc+52 -> ... cleanly) but replacing the FINAL guard  *)
(* resolution (SIk_RESOLVE, which proves the mid-guard NOT taken -> continue)   *)
(* with a TAKEN resolution (JA_TAKEN_GT -> pc+314) at whichever sub-iter the    *)
(* exit occurs, then SCALAR_TAIL_AT_P. Because the exit point is data-dependent *)
(* (which guard fires), case-split per sub-iter: ASM_CASES niblen(q+4k)>248,    *)
(* run SIk to its guard, then branch. Reuse PREFIX_G_FULL_TAC for the head +    *)
(* sub-iter-1 gather (it's already optimized); do NOT raw-VSTEP the vectors.    *)

(* ========================================================================= *)
(* DETAILED CONTINUATION PLAN (2026-06-23, after deeper analysis).            *)
(*                                                                            *)
(* The exit block reuses the SAME SIMD gather as CLEAN_BODY. The gather        *)
(* machinery lives in (load order): .prefix_g_full_tac (PREFIX_G_FULL_TAC,     *)
(* head+sub-iter1 -> s23, ends RIP=pc+163), .si2_integrated (SI2_INTEGRATED,   *)
(* -> s35/pc+215), .si3_integrated (-> s47/pc+268), .si4_integrated            *)
(* (-> s57/pc+52). Each SIk_INTEGRATED = gather + store-fold + counter +       *)
(* SIk_MG_TAC (proves count<=248 bound) + SIk_RESOLVE (resolves mid-guard      *)
(* COND to CONTINUE via JA_NOT_TAKEN_LE).                                      *)
(*                                                                            *)
(* THE EXIT BLOCK = run these gather tactics, but at the sub-iter where the    *)
(* WOP exit fires, the count EXCEEDS 248 so SIk_MG_TAC's bound (<=248) is       *)
(* FALSE and SIk_RESOLVE picks the WRONG branch. Need exit variants:           *)
(*                                                                            *)
(* PLAN (per-sub-iter case split, k=1..4):                                    *)
(*  ASM_CASES_TAC `LENGTH(REJ_SAMPLE_ETA4_BYTES(SUB_LIST(0,q+4k) inlist)) <= 248` *)
(*   - if <=248 (CONTINUE): the sub-iter's mid-guard is NOT taken; run the     *)
(*     CLEAN sub-iter machinery (PREFIX_G_FULL for k=1; SIk_INTEGRATED else),  *)
(*     which needs niblen(q+4k)<=248 -- now available -- and continues to the  *)
(*     next sub-iter. Recurse to sub-iter k+1.                                 *)
(*   - if >248 (EXIT): run the sub-iter's GATHER+STORE only (PREFIX_G/SIk's    *)
(*     gather part, NOT the RESOLVE), reaching the mid-guard with the store    *)
(*     folded (res holds REJ(SUB(0,q+4k))); then resolve the mid-guard COND    *)
(*     TAKEN via JA_TAKEN_GT (count q+4k's niblen > 248, and < 2^32 since       *)
(*     <=256); RIP -> pc+314. Establish niblen(q+4k)<=256 (OUTLEN0_LE_256_     *)
(*     FROM_SUBITER). Then MP_TAC MLDSA_REJ_UNIFORM_ETA4_SCALAR_TAIL_AT_P @     *)
(*     (p=q+4k) and ENSURES_TRANS/sequence to pc+402.                          *)
(*  Sub-iter 4 has NO mid-guard (jmp pc+52); after it, pos=16N=q+16 and the    *)
(*   HEAD guard (back at pc+52) fires (WOP: 256<16N or niblen(16N)>248) -> the  *)
(*   exit is at p=16N via the head guard. This is the "block completes" arm:   *)
(*   run all 4 clean sub-iters (= CLEAN_BODY body, ends pc+52 with pos=16N,     *)
(*   niblen(16N)), then ONE head-guard step resolving TAKEN -> pc+314 @ p=16N,  *)
(*   niblen(16N)<=256 (=248+8 via OUTLEN0_LE_256), SCALAR_TAIL_AT_P -> pc+402.  *)
(*                                                                            *)
(* NEED a callable "gather-only" form of PREFIX_G_FULL / SIk (without the      *)
(* final SIk_RESOLVE not-taken step) -- factor SIk_INTEGRATED = SIk_GATHER ...  *)
(* SIk_MG_TAC THEN SIk_RESOLVE; the gather+fold parts are reusable, only the    *)
(* RESOLVE differs (taken vs not-taken). The CONTINUE arm can call the full     *)
(* SIk_INTEGRATED directly (guards not-taken, niblen<=248 available).          *)
(*                                                                            *)
(* SCALE: ~4 case-splits, each reusing existing gather tactics. The CONTINUE   *)
(* arms are nearly free (existing tactics); the EXIT arms need the gather +    *)
(* JA_TAKEN_GT resolution + SCALAR_TAIL_AT_P. The "all-clean then head-exit"   *)
(* arm reuses CLEAN_BODY's body wholesale + one head guard.                    *)
(* ========================================================================= *)

(* ========================================================================= *)
(* CORRECTION (2026-06-23, after ASM_CASES niblen(16N)<=248 on the exit goal): *)
(* The "clean arm" (niblen(16N)<=248) is NOT free. In that arm, WOP forces      *)
(* 256<16N (the other disjunct), i.e. N=17, 16N=272, q=16(N-1)=256. So the     *)
(* exit block processes bytes 256..271 (pos 256->272). CLEAN_BODY requires      *)
(* 16*(i+1)=16N<=256 -- FALSE here (272>256). So CLEAN_BODY does NOT apply to   *)
(* the last block. The head guard cmp ecx,256 at pos=256 is NOT taken (256>256  *)
(* false), so it enters the sub-iters; after the block pos=272, jmp pc+52, then *)
(* cmp ecx,256 with 272>256 TRUE -> exit at p=272 (offset-exit).                *)
(*                                                                            *)
(* CONSEQUENCE: BOTH arms need real SIMD stepping not covered by CLEAN_BODY:    *)
(*  - clean/offset arm (N=17, q=256): step the full q=256 block (4 sub-iters,   *)
(*    all mid-guards not-taken since niblen<=248) to pos=272, then head guard   *)
(*    TAKEN -> pc+314 @ p=272; SCALAR_TAIL_AT_P (p=272 is the offset/base case).*)
(*    This needs a CLEAN_BODY-variant WITHOUT the 16(i+1)<=256 constraint (the   *)
(*    gather/store machinery itself doesn't need pos<=256, only the store       *)
(*    address bound res+4*niblen which is <=248*4 < 1024 ok). Could re-prove     *)
(*    CLEAN_BODY with hyp `16*(i+1)<=272` instead of <=256 (check SUBITER_      *)
(*    BLOCK_BYTES / the store-fold lemmas allow it).                            *)
(*  - mid-exit arm (niblen(16N)>248): a mid-guard fires; per-sub-iter branch.   *)
(*                                                                            *)
(* So the cleanest unifying move: re-prove a BODY-to-pc318 lemma covering the   *)
(* last block that ends at pc+314 with the exit position p (5-way: head-at-q    *)
(* not-taken always since niblen(q)<=248; mid-guards 1/2/3 taken-or-not;        *)
(* head-at-16N taken). Reuses the gather/store tactics with branch resolution.  *)
(* ========================================================================= *)

(* ========================================================================= *)
(* EXPERIMENT (2026-06-23): relaxing CLEAN_BODY's hyp 16*(i+1)<=256 -> <=272.  *)
(* GOAL: a single CLEAN_BODY covering both clean blocks (#8) AND the exit       *)
(* block's offset arm (N=17, q=256, block 256..271). PREFIX_G_FULL_TAC SUCCEEDS *)
(* with <=272 (head-guard derivation 16*i<=256 follows from 16*(i+1)<=272 since *)
(* i<=16 => 16i<=256). BUT SI2_INTEGRATED then fails with "find" -- some find    *)
(* in its W-fold block is sensitive to the assumption set under <=272 (NOT the  *)
(* i116/i_le lookups, which were updated and DO match; the failing find is       *)
(* elsewhere in the bg2/mthm2/pfth2/storef0/acc1_ident chain). REVERTED to the   *)
(* proven <=256 chain to protect #8's CLEAN_BODY.                               *)
(* NEXT: to make CLEAN_BODY_272 work, instrument SI2_INTEGRATED's W-block finds  *)
(* (wrap each `find` with a label) to identify the failing one, then make that   *)
(* find-predicate structural (not exact-term) or supply the missing hyp. The      *)
(* sed edits were: 16*(i+1)<=256 -> <=272 in clean_body_build.ml + .prefix_g_     *)
(* full_tac + .si{2,3,4}_{full,integrated}.ml (8 files). Re-apply then debug the  *)
(* SI2 find. Once CLEAN_BODY_272 proves, the exit offset arm = CLEAN_BODY_272 @   *)
(* i=N-1 (gives pc+52 @ pos=16N=272) + head guard cmp ecx,256 TAKEN (272>256) ->  *)
(* pc+314 @ p=272 + SCALAR_TAIL_AT_P. The mid-exit arm (niblen(16N)>248) still     *)
(* needs per-sub-iter taken-guard branching separately.                          *)
(* ========================================================================= *)

(* ========================================================================= *)
(* DEFINITIVE FINDING (2026-06-23): the <=272 global relaxation of CLEAN_BODY  *)
(* is a DEAD END. PREFIX_G_FULL_TAC succeeds at <=272, but SI2_INTEGRATED then  *)
(* fails with "MP: theorems do not agree" in its store-fold W-block -- the SI    *)
(* machinery encodes <=256-specific reasoning BEYOND the surface 16*(i+1)<=256   *)
(* hypothesis (deep MPs in the count-bound / fold chain, not just the i116/i_le  *)
(* lookups which were updated fine). Reverted all 8 files to the proven <=256.   *)
(*                                                                            *)
(* So the exit block CANNOT reuse CLEAN_BODY for the N=17/pos-256 offset arm.   *)
(* Both exit arms need dedicated gather stepping. The realistic path is to       *)
(* build a fresh EXIT_BLOCK proof that steps the last block's 4 sub-iters with   *)
(* the gather machinery's COMPONENT tactics (the bg1-4 gather foralls, the        *)
(* store-fold lemmas SUBITER_STORE_SPEC/POSTCOND/FOLD_STEP, the maskbit/pf_target *)
(* /tab tactics) re-assembled WITHOUT the <=256 count-bound assumptions, and with *)
(* per-mid-guard ASM_CASES (JA_TAKEN_GT exit / JA_NOT_TAKEN_LE continue). This is *)
(* genuinely a from-near-scratch re-assembly of the gather (the existing SIk      *)
(* tactics are too <=256-coupled to reuse directly), comparable to a chunk of     *)
(* the original CLEAN_BODY build. The gather COMPONENT lemmas (SUBITER_STORE_*,    *)
(* the per-lane gather foralls bg1-4) ARE reusable; the SIk_INTEGRATED            *)
(* WRAPPERS are not. *)
(* ========================================================================= *)
