(* ========================================================================= *)
(* EXIT-BLOCK proof progress (2026-06-23) — the LAST goal of cheat-free        *)
(* MLDSA_REJ_UNIFORM_ETA4_CORRECT. Starts from CORRECT_SCAFFOLD_TAC's leftover  *)
(* goal (after ABBREV q = 16*(N-1)). Entry @ pc+56: RAX=word(niblen(q)),        *)
(* RCX=word q, res holds REJ(SUB(0,q)), YMM2/3/4 set; hyps q<=256,              *)
(* niblen(q)<=248 (REJ_NIBBLES + REJ_SAMPLE forms), 16N=q+16, q+16<=272.        *)
(*                                                                            *)
(* VALIDATED PREFIX (head guards, both fall through):                          *)
(*   ENSURES_INIT_TAC "s0" THEN                                                *)
(*   <JA_NOT_TAKEN_LE fact for cmp eax,248 @ niblen(q)<=248> THEN              *)
(*   <JA_NOT_TAKEN_LE fact for cmp ecx,256 @ q<=256> THEN                      *)
(*   X86_STEPS_TAC EXEC (1--4)  ==> RIP s4 = pc+79 (vpmovzxbw, sub-iter1 start) *)
(* The two JA facts (exact terms):                                            *)
(*  ~(&(val(word_zx(word(LENGTH(REJ_SAMPLE_ETA4_BYTES(SUB_LIST(0,q)inlist):int32 list)):int64):int32)):int - &248 = &(val(word_sub(word_zx(word(LENGTH ...):int64):int32)(word 248):int32))) \/ val(word_sub ...)=0   [MATCH_MP_TAC JA_NOT_TAKEN_LE; ARITH] *)
(*  ~(&(val(word_zx(word q:int64):int32)):int - &256 = &(val(word_sub(word_zx(word q:int64):int32)(word 256):int32))) \/ val(...)=0   [JA_NOT_TAKEN_LE; q<=256] *)
(*                                                                            *)
(* REMAINING (the genuine work): 4 sub-iters from pc+79. Each sub-iter k        *)
(* (k=0..3, at pos q+4k) does gather+store+counter then a `cmp eax,248; ja`     *)
(* mid-guard (sub-iters 1,2,3) or wraps to head (sub-iter 4 -> jmp pc+56 then   *)
(* head guard). At sub-iter k's guard: ASM_CASES_TAC on whether                 *)
(* niblen(q+4(k+1)) > 248 (count-exit) OR q+4(k+1) reaches 256 (offset):        *)
(*   - NOT taken: continue (reuse SI{k+1} gather/store/fold from .si*_full /    *)
(*     .si*_fold_*; they fold the store into res prefix and resolve the guard   *)
(*     not-taken via JA_NOT_TAKEN_LE -- ALREADY the SIk_MG_TAC/SIk_RESOLVE      *)
(*     pattern).                                                                *)
(*   - TAKEN: resolve RIP COND -> pc+318 via JA_TAKEN_GT (in .subiter_bridge_   *)
(*     lemmas.ml), with exit position p=q+4(k+1) [or q for the entry head, but  *)
(*     that's not taken since niblen(q)<=248]; establish niblen(p)<=256 via     *)
(*     OUTLEN0_LE_256_FROM_SUBITER; then MP_TAC                                 *)
(*     MLDSA_REJ_UNIFORM_ETA4_SCALAR_TAIL_AT_P @ (concrete p) and discharge     *)
(*     pc+318 -> pc+406 (ENSURES_TRANS / sequence).                            *)
(* NOTE the offset-exit (q reaches 256) only matters when 256<16N (N=17,        *)
(* pos=272 region); the count-exit (niblen>248) is the common case. The WOP     *)
(* hyp `256<16*N \/ 248<niblen(16N)` (with 16N=q+16) guarantees SOME guard      *)
(* fires within this block (else the block completes clean and the next head    *)
(* guard at pos q+16=16N fires).                                                *)
(*                                                                            *)
(* The SI{1,2,3,4} tactics are loaded (.si*_full, .si*_integrated,             *)
(* .si*_fold_*). They were built for the CLEAN body (all-not-taken). For the    *)
(* exit block, the LAST sub-iter before exit needs the TAKEN branch instead --  *)
(* adapt SIk_RESOLVE to resolve the COND via JA_TAKEN_GT (then SCALAR_TAIL_AT_P)*)
(* rather than JA_NOT_TAKEN_LE. *)
(* ========================================================================= *)
Printf.printf "EXIT_BLOCK_PROGRESS: head guards validated (pc+56 -> pc+79); 4 sub-iters + per-guard exit branches remain. See comment.\n";;

(* ⚠️ PERFORMANCE (2026-06-23): raw X86_VSTEPS_TAC over the SIMD gather is FAR  *)
(* too slow -- 6 vector instrs (pc+79..pc+106: vpmovzxbw/vpand/vpshufb/...)     *)
(* took ~286s. MUST use the specialized CLEAN_BODY vector tactics instead:      *)
(* PREFIX_G_FULL_TAC (head+sub-iter1 -> s23) and SI2/3/4_INTEGRATED, which      *)
(* REABBREV the vector intermediates (f0sub/f1bnd/chunk0/mask8/pshuf/tab) and   *)
(* avoid the term blowup. The exit block should be proven by RE-RUNNING those   *)
(* SAME tactics (they step pc+56 -> ... cleanly) but replacing the FINAL guard  *)
(* resolution (SIk_RESOLVE, which proves the mid-guard NOT taken -> continue)   *)
(* with a TAKEN resolution (JA_TAKEN_GT -> pc+318) at whichever sub-iter the    *)
(* exit occurs, then SCALAR_TAIL_AT_P. Because the exit point is data-dependent *)
(* (which guard fires), case-split per sub-iter: ASM_CASES niblen(q+4k)>248,    *)
(* run SIk to its guard, then branch. Reuse PREFIX_G_FULL_TAC for the head +    *)
(* sub-iter-1 gather (it's already optimized); do NOT raw-VSTEP the vectors.    *)

(* ========================================================================= *)
(* DETAILED CONTINUATION PLAN (2026-06-23, after deeper analysis).            *)
(*                                                                            *)
(* The exit block reuses the SAME SIMD gather as CLEAN_BODY. The gather        *)
(* machinery lives in (load order): .prefix_g_full_tac (PREFIX_G_FULL_TAC,     *)
(* head+sub-iter1 -> s23, ends RIP=pc+167), .si2_integrated (SI2_INTEGRATED,   *)
(* -> s35/pc+219), .si3_integrated (-> s47/pc+272), .si4_integrated            *)
(* (-> s57/pc+56). Each SIk_INTEGRATED = gather + store-fold + counter +       *)
(* SIk_MG_TAC (proves count<=248 bound) + SIk_RESOLVE (resolves mid-guard      *)
(* COND to CONTINUE via JA_NOT_TAKEN_LE).                                      *)
(*                                                                            *)
(* THE EXIT BLOCK = run these gather tactics, but at the sub-iter where the    *)
(* WOP exit fires, the count EXCEEDS 248 so SIk_MG_TAC's bound (<=248) is       *)
(* FALSE and SIk_RESOLVE picks the WRONG branch. Need exit variants:           *)
(*                                                                            *)
(* PLAN (per-sub-iter case split, k=1..4):                                    *)
(*  ASM_CASES_TAC `LENGTH(REJ_SAMPLE_ETA4_BYTES(SUB_LIST(0,q+4k) inlist)) <= 248` *)
(*   - if <=248 (CONTINUE): the sub-iter's mid-guard is NOT taken; run the     *)
(*     CLEAN sub-iter machinery (PREFIX_G_FULL for k=1; SIk_INTEGRATED else),  *)
(*     which needs niblen(q+4k)<=248 -- now available -- and continues to the  *)
(*     next sub-iter. Recurse to sub-iter k+1.                                 *)
(*   - if >248 (EXIT): run the sub-iter's GATHER+STORE only (PREFIX_G/SIk's    *)
(*     gather part, NOT the RESOLVE), reaching the mid-guard with the store    *)
(*     folded (res holds REJ(SUB(0,q+4k))); then resolve the mid-guard COND    *)
(*     TAKEN via JA_TAKEN_GT (count q+4k's niblen > 248, and < 2^32 since       *)
(*     <=256); RIP -> pc+318. Establish niblen(q+4k)<=256 (OUTLEN0_LE_256_     *)
(*     FROM_SUBITER). Then MP_TAC MLDSA_REJ_UNIFORM_ETA4_SCALAR_TAIL_AT_P @     *)
(*     (p=q+4k) and ENSURES_TRANS/sequence to pc+406.                          *)
(*  Sub-iter 4 has NO mid-guard (jmp pc+56); after it, pos=16N=q+16 and the    *)
(*   HEAD guard (back at pc+56) fires (WOP: 256<16N or niblen(16N)>248) -> the  *)
(*   exit is at p=16N via the head guard. This is the "block completes" arm:   *)
(*   run all 4 clean sub-iters (= CLEAN_BODY body, ends pc+56 with pos=16N,     *)
(*   niblen(16N)), then ONE head-guard step resolving TAKEN -> pc+318 @ p=16N,  *)
(*   niblen(16N)<=256 (=248+8 via OUTLEN0_LE_256), SCALAR_TAIL_AT_P -> pc+406.  *)
(*                                                                            *)
(* NEED a callable "gather-only" form of PREFIX_G_FULL / SIk (without the      *)
(* final SIk_RESOLVE not-taken step) -- factor SIk_INTEGRATED = SIk_GATHER ...  *)
(* SIk_MG_TAC THEN SIk_RESOLVE; the gather+fold parts are reusable, only the    *)
(* RESOLVE differs (taken vs not-taken). The CONTINUE arm can call the full     *)
(* SIk_INTEGRATED directly (guards not-taken, niblen<=248 available).          *)
(*                                                                            *)
(* SCALE: ~4 case-splits, each reusing existing gather tactics. The CONTINUE   *)
(* arms are nearly free (existing tactics); the EXIT arms need the gather +    *)
(* JA_TAKEN_GT resolution + SCALAR_TAIL_AT_P. The "all-clean then head-exit"   *)
(* arm reuses CLEAN_BODY's body wholesale + one head guard.                    *)
(* ========================================================================= *)
