(* ========================================================================= *)
(* EXIT-BLOCK proof progress (2026-06-23) — the LAST goal of cheat-free        *)
(* MLDSA_REJ_UNIFORM_ETA4_CORRECT. Starts from CORRECT_SCAFFOLD_TAC's leftover  *)
(* goal (after ABBREV q = 16*(N-1)). Entry @ pc+56: RAX=word(niblen(q)),        *)
(* RCX=word q, res holds REJ(SUB(0,q)), YMM2/3/4 set; hyps q<=256,              *)
(* niblen(q)<=248 (REJ_NIBBLES + REJ_SAMPLE forms), 16N=q+16, q+16<=272.        *)
(*                                                                            *)
(* VALIDATED PREFIX (head guards, both fall through):                          *)
(*   ENSURES_INIT_TAC "s0" THEN                                                *)
(*   <JA_NOT_TAKEN_LE fact for cmp eax,248 @ niblen(q)<=248> THEN              *)
(*   <JA_NOT_TAKEN_LE fact for cmp ecx,256 @ q<=256> THEN                      *)
(*   X86_STEPS_TAC EXEC (1--4)  ==> RIP s4 = pc+79 (vpmovzxbw, sub-iter1 start) *)
(* The two JA facts (exact terms):                                            *)
(*  ~(&(val(word_zx(word(LENGTH(REJ_SAMPLE_ETA4_BYTES(SUB_LIST(0,q)inlist):int32 list)):int64):int32)):int - &248 = &(val(word_sub(word_zx(word(LENGTH ...):int64):int32)(word 248):int32))) \/ val(word_sub ...)=0   [MATCH_MP_TAC JA_NOT_TAKEN_LE; ARITH] *)
(*  ~(&(val(word_zx(word q:int64):int32)):int - &256 = &(val(word_sub(word_zx(word q:int64):int32)(word 256):int32))) \/ val(...)=0   [JA_NOT_TAKEN_LE; q<=256] *)
(*                                                                            *)
(* REMAINING (the genuine work): 4 sub-iters from pc+79. Each sub-iter k        *)
(* (k=0..3, at pos q+4k) does gather+store+counter then a `cmp eax,248; ja`     *)
(* mid-guard (sub-iters 1,2,3) or wraps to head (sub-iter 4 -> jmp pc+56 then   *)
(* head guard). At sub-iter k's guard: ASM_CASES_TAC on whether                 *)
(* niblen(q+4(k+1)) > 248 (count-exit) OR q+4(k+1) reaches 256 (offset):        *)
(*   - NOT taken: continue (reuse SI{k+1} gather/store/fold from .si*_full /    *)
(*     .si*_fold_*; they fold the store into res prefix and resolve the guard   *)
(*     not-taken via JA_NOT_TAKEN_LE -- ALREADY the SIk_MG_TAC/SIk_RESOLVE      *)
(*     pattern).                                                                *)
(*   - TAKEN: resolve RIP COND -> pc+318 via JA_TAKEN_GT (in .subiter_bridge_   *)
(*     lemmas.ml), with exit position p=q+4(k+1) [or q for the entry head, but  *)
(*     that's not taken since niblen(q)<=248]; establish niblen(p)<=256 via     *)
(*     OUTLEN0_LE_256_FROM_SUBITER; then MP_TAC                                 *)
(*     MLDSA_REJ_UNIFORM_ETA4_SCALAR_TAIL_AT_P @ (concrete p) and discharge     *)
(*     pc+318 -> pc+406 (ENSURES_TRANS / sequence).                            *)
(* NOTE the offset-exit (q reaches 256) only matters when 256<16N (N=17,        *)
(* pos=272 region); the count-exit (niblen>248) is the common case. The WOP     *)
(* hyp `256<16*N \/ 248<niblen(16N)` (with 16N=q+16) guarantees SOME guard      *)
(* fires within this block (else the block completes clean and the next head    *)
(* guard at pos q+16=16N fires).                                                *)
(*                                                                            *)
(* The SI{1,2,3,4} tactics are loaded (.si*_full, .si*_integrated,             *)
(* .si*_fold_*). They were built for the CLEAN body (all-not-taken). For the    *)
(* exit block, the LAST sub-iter before exit needs the TAKEN branch instead --  *)
(* adapt SIk_RESOLVE to resolve the COND via JA_TAKEN_GT (then SCALAR_TAIL_AT_P)*)
(* rather than JA_NOT_TAKEN_LE. *)
(* ========================================================================= *)
Printf.printf "EXIT_BLOCK_PROGRESS: head guards validated (pc+56 -> pc+79); 4 sub-iters + per-guard exit branches remain. See comment.\n";;
