(* ========================================================================= *)
(* SCALAR_TAIL_RUN: the byte-loop-to-exit lemma, by strong induction on the   *)
(* byte-budget d (bound on 272-p). Subsumes the K-1 loop + terminal trip in   *)
(* one recursion, avoiding the ENSURES_WHILE off-by-one. From any pc+318 with  *)
(* RAX=outlen(p), RCX=p, res=REJ(SUB(0,p)), runs to pc+406 with capped output. *)
(* Then MLDSA_REJ_UNIFORM_ETA4_SCALAR_TAIL = RUN specialized at p=16N (d=272). *)
(* Load after main file + .scalar_tail_lemmas + .scalar_tail_build + .scalar_body_lemma. *)
(*                                                                            *)
(* INDUCTION STRUCTURE (INDUCT_TAC on d):                                     *)
(*  base d=0: p=272 (from 272-p<=0 /\ p<=272). Both top guards: cmp eax,256    *)
(*    (taken if outlen272>=256 -> pc+406) else cmp ecx,272 jae TAKEN -> pc+406.*)
(*    Output: count-exit (outlen>=256) via SUB_LIST_256_PREFIX_GE+MEM_PREFIX_256;*)
(*    offset-exit (outlen<256) via SUB_LIST_256_LE (cap identity) + SUB(0,272)=inlist.*)
(*  step d=SUC d': three sub-cases at pos p:                                  *)
(*   (a) outlen(p)>=256: count-exit now (cmp eax,256 jae TAKEN -> pc+406).      *)
(*   (b) outlen(p)<256 /\ p=272: offset-exit (cmp ecx,272 jae TAKEN -> pc+406). *)
(*   (c) outlen(p)<256 /\ p<272: sub-case on mid-exit (outlen=255 /\ low<9):    *)
(*     - mid-exit: step pc+318..pc+373 (cmp eax,256 nt; cmp ecx,272 nt; load;  *)
(*       inc rcx; low nibble store; inc rax -> outlen 256; cmp eax,256 jae TAKEN*)
(*       -> pc+406). Output count-exit at p+1 (low nibble only) via the cap.    *)
(*     - clean: MATCH_MP SCALAR_TAIL_BODY (p,outlen(p)) [precond ~(L=255/\low<9)*)
(*       holds: this is the not-mid-exit case] giving pc+318->pc+318 at p+1,    *)
(*       then ENSURES_TRANS with IH at d' (272-(p+1)<=d' since 272-p<=SUC d').  *)
(* GUARD-TAKEN exit stepping (the new ISA work): at pc+318, cmp eax,256;        *)
(*   jae(Condition_NB) TAKEN when outlen>=256 -> JAE_TAKEN_GE-style fact on RAX *)
(*   makes X86_VSTEPS resolve RIP->pc+406. Similarly cmp ecx,272 at pc+325.     *)
(* ========================================================================= *)

(* (proof under construction — see eta4-scalar-tail-progress.md for the exact
   validated setup: SUB_LIST_BYTE_272 for p=272, ENSURES_INIT, case-splits,
   SCALAR_TAIL_BODY + IH composition via ENSURES_TRANS in the clean recursive case.) *)
